name: helpers
environment:
  sdk: '>=2.16.0 <3.0.0'

dependencies:
  path: ^1.8.3
  yaml: ^3.1.1
  args: ^2.4.0
  collection: ^1.17.1
  pub_semver: ^2.1.3
  http: ^1.0.0
  pub:
    git:
     url: https://github.com/dart-lang/pub
     ref: a16763a93b5050c6a9d917fca5a132cfcb00f1a9
